// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTV0bqK1r3Kbgrn-57nDcrFlayyLneAgg',
    appId: '1:1026182273892:android:47a9f91eb42356dde6b871',
    messagingSenderId: '1026182273892',
    projectId: 'nids-de-poule-1028d',
    storageBucket: 'nids-de-poule-1028d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyQJIpaVYicdxFvV7wY5EQlaC_V3tPOeE',
    appId: '1:1026182273892:ios:4ee2a2c038053f3fe6b871',
    messagingSenderId: '1026182273892',
    projectId: 'nids-de-poule-1028d',
    storageBucket: 'nids-de-poule-1028d.firebasestorage.app',
    iosBundleId: 'com.example.froge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyQJIpaVYicdxFvV7wY5EQlaC_V3tPOeE',
    appId: '1:1026182273892:ios:4ee2a2c038053f3fe6b871',
    messagingSenderId: '1026182273892',
    projectId: 'nids-de-poule-1028d',
    storageBucket: 'nids-de-poule-1028d.firebasestorage.app',
    iosBundleId: 'com.example.froge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3os9IZ_9pQSthAncbJy9c2RAJS4q8JqU',
    appId: '1:1026182273892:web:28f04563502e893be6b871',
    messagingSenderId: '1026182273892',
    projectId: 'nids-de-poule-1028d',
    authDomain: 'nids-de-poule-1028d.firebaseapp.com',
    storageBucket: 'nids-de-poule-1028d.firebasestorage.app',
    measurementId: 'G-GT182KYWNT',
  );

}